version: "3.3"
services:

  frontend:
    image: '${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}'
    build:
      context: .
      args:
        # 'dev' or 'production'
        FRONTEND_ENV: ${FRONTEND_ENV-dev}
